[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.ci]
fuzz = { runs = 1000 }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC}"
local = "http://127.0.0.1:8545"

[etherscan]
arbitrum_sepolia = { key = "${ETHERSCAN_API_KEY}" }
